#ifndef WIFLYMQTTMONITOR_FTOLED_CONFIG_H_
#define WIFLYMQTTMONITOR_FTOLED_CONFIG_H_


#include <FTOLED.h>

const byte PIN_CS = 7;
const byte PIN_DC = 2;
const byte PIN_RESET = 3;

OLED oled(PIN_CS, PIN_DC, PIN_RESET);


#endif  /* WIFLYMQTTMONITOR_FTOLED_CONFIG_H_ */

